/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\car.gltf 
Author: Stéphane Agullo (https://sketchfab.com/sa3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotus-elise-75e9045ac1af4cdbb69318108c81edfd
Title: LOTUS ÉLISE
*/

import React, { useEffect, useRef } from "react";
import {
  useGLTF,
  useAnimations,
  Environment,
  OrbitControls,
  PerspectiveCamera,
} from "@react-three/drei";

export default function Car(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/car/car.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <>
      <PerspectiveCamera position={[20, 8, -40]} makeDefault />
      <OrbitControls target={[13, 0, 0]} />
      <Environment preset="sunset" />
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.014}
          >
            <group
              name="bc417e1d5436463cb3d05631c0bcff84fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group name="LOTUS-def3Layer1" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer1_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer1_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer1_CARfeu_0"
                      geometry={nodes["LOTUS-def3Layer1_CARfeu_0"].geometry}
                      material={materials["CAR.feu"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer1_CARcarros_0"
                      geometry={nodes["LOTUS-def3Layer1_CARcarros_0"].geometry}
                      material={materials["CAR.carros"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer1_CARgris_0"
                      geometry={nodes["LOTUS-def3Layer1_CARgris_0"].geometry}
                      material={materials["CAR.gris"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer2"
                    position={[-75, 35.043, -121]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                  >
                    <mesh
                      name="LOTUS-def3Layer2_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer2_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer2_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer2_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer2_CARlogo_0"
                      geometry={nodes["LOTUS-def3Layer2_CARlogo_0"].geometry}
                      material={materials["CAR.logo"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer16" position={[75, 35.096, -121]}>
                    <mesh
                      name="LOTUS-def3Layer16_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer16_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer16_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer16_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer16_CARlogo_0"
                      geometry={nodes["LOTUS-def3Layer16_CARlogo_0"].geometry}
                      material={materials["CAR.logo"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer17"
                    position={[-75, 35.08, 125]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                  >
                    <mesh
                      name="LOTUS-def3Layer17_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer17_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer17_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer17_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer17_CARlogo_0"
                      geometry={nodes["LOTUS-def3Layer17_CARlogo_0"].geometry}
                      material={materials["CAR.logo"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer18" position={[75, 35.084, 125]}>
                    <mesh
                      name="LOTUS-def3Layer18_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer18_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer18_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer18_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer18_CARlogo_0"
                      geometry={nodes["LOTUS-def3Layer18_CARlogo_0"].geometry}
                      material={materials["CAR.logo"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer6" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer6_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer6_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer6_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARverre_0"
                      geometry={nodes["LOTUS-def3Layer6_CARverre_0"].geometry}
                      material={materials["CAR.verre"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARfeu-2_0"
                      geometry={nodes["LOTUS-def3Layer6_CARfeu-2_0"].geometry}
                      material={materials["CAR.feu-2"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARcarros_0"
                      geometry={nodes["LOTUS-def3Layer6_CARcarros_0"].geometry}
                      material={materials["CAR.carros"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARecusson_0"
                      geometry={nodes["LOTUS-def3Layer6_CARecusson_0"].geometry}
                      material={materials["CAR.ecusson"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-arr-bas_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-arr-bas_0"].geometry
                      }
                      material={materials["CAR.lamp-arr-bas"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-arr-orange_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-arr-orange_0"].geometry
                      }
                      material={materials["CAR.lamp-arr-orange"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-arr-rouge_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-arr-rouge_0"].geometry
                      }
                      material={materials["CAR.lamp-arr-rouge"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-avant-bas_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-avant-bas_0"].geometry
                      }
                      material={materials["CAR.lamp-avant-bas"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-avant-haut_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-avant-haut_0"].geometry
                      }
                      material={materials["CAR.lamp-avant-haut"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARlamp-avant-milieu_0"
                      geometry={
                        nodes["LOTUS-def3Layer6_CARlamp-avant-milieu_0"]
                          .geometry
                      }
                      material={materials["CAR.lamp-avant-milieu"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer6_CARplaque_0"
                      geometry={nodes["LOTUS-def3Layer6_CARplaque_0"].geometry}
                      material={materials["CAR.plaque"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer7"
                    position={[-86.301, 60.841, -66.915]}
                  >
                    <mesh
                      name="LOTUS-def3Layer7_CARgris_0"
                      geometry={nodes["LOTUS-def3Layer7_CARgris_0"].geometry}
                      material={materials["CAR.gris"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer7_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer7_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer7_CARcarros_0"
                      geometry={nodes["LOTUS-def3Layer7_CARcarros_0"].geometry}
                      material={materials["CAR.carros"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer7_CARmirroir_0"
                      geometry={nodes["LOTUS-def3Layer7_CARmirroir_0"].geometry}
                      material={materials["CAR.mirroir"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer7_CARverre_0"
                      geometry={nodes["LOTUS-def3Layer7_CARverre_0"].geometry}
                      material={materials["CAR.verre"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer7_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer7_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer8"
                    position={[86.288, 60.841, -66.913]}
                  >
                    <mesh
                      name="LOTUS-def3Layer8_CARgris_0"
                      geometry={nodes["LOTUS-def3Layer8_CARgris_0"].geometry}
                      material={materials["CAR.gris"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer8_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer8_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer8_CARcarros_0"
                      geometry={nodes["LOTUS-def3Layer8_CARcarros_0"].geometry}
                      material={materials["CAR.carros"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer8_CARmirroir_0"
                      geometry={nodes["LOTUS-def3Layer8_CARmirroir_0"].geometry}
                      material={materials["CAR.mirroir"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer8_CARverre_0"
                      geometry={nodes["LOTUS-def3Layer8_CARverre_0"].geometry}
                      material={materials["CAR.verre"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer8_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer8_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer9" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer9_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer9_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer9_CARverre_0"
                      geometry={nodes["LOTUS-def3Layer9_CARverre_0"].geometry}
                      material={materials["CAR.verre"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer9_CARmirroir_0"
                      geometry={nodes["LOTUS-def3Layer9_CARmirroir_0"].geometry}
                      material={materials["CAR.mirroir"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer10" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer10_CARchrome_0"
                      geometry={nodes["LOTUS-def3Layer10_CARchrome_0"].geometry}
                      material={materials["CAR.chrome"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer10_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer10_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer11" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer11_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer11_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                  </group>
                  <group name="LOTUS-def3Layer5" position={[0, 60.841, 0]}>
                    <mesh
                      name="LOTUS-def3Layer5_CARgris_0"
                      geometry={nodes["LOTUS-def3Layer5_CARgris_0"].geometry}
                      material={materials["CAR.gris"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer5_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer5_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer5_CARverre_0"
                      geometry={nodes["LOTUS-def3Layer5_CARverre_0"].geometry}
                      material={materials["CAR.verre"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer12"
                    position={[-30.191, 71.321, -43.763]}
                    rotation={[-0.199, 0, 0]}
                  >
                    <mesh
                      name="LOTUS-def3Layer12_CARgris_0"
                      geometry={nodes["LOTUS-def3Layer12_CARgris_0"].geometry}
                      material={materials["CAR.gris"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer12_CARlogo_0"
                      geometry={nodes["LOTUS-def3Layer12_CARlogo_0"].geometry}
                      material={materials["CAR.logo"]}
                    />
                    <mesh
                      name="LOTUS-def3Layer12_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer12_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                  </group>
                  <group
                    name="Girl1"
                    position={[-31.155, -42.943, 6.97]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={0.9}
                  >
                    <group name="Object_72">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_74" />
                      <skinnedMesh
                        name="Object_75"
                        geometry={nodes.Object_75.geometry}
                        material={materials["NANA-black"]}
                        skeleton={nodes.Object_75.skeleton}
                      />
                      <skinnedMesh
                        name="Object_76"
                        geometry={nodes.Object_76.geometry}
                        material={materials["NANA-combi"]}
                        skeleton={nodes.Object_76.skeleton}
                      />
                      <skinnedMesh
                        name="Object_77"
                        geometry={nodes.Object_77.geometry}
                        material={materials["NANA-po"]}
                        skeleton={nodes.Object_77.skeleton}
                      />
                      <skinnedMesh
                        name="Object_78"
                        geometry={nodes.Object_78.geometry}
                        material={materials["NANA-oeil"]}
                        skeleton={nodes.Object_78.skeleton}
                      />
                      <skinnedMesh
                        name="Object_79"
                        geometry={nodes.Object_79.geometry}
                        material={materials["NANA-verre"]}
                        skeleton={nodes.Object_79.skeleton}
                      />
                      <skinnedMesh
                        name="Object_80"
                        geometry={nodes.Object_80.geometry}
                        material={materials["NANA-lang"]}
                        skeleton={nodes.Object_80.skeleton}
                      />
                    </group>
                  </group>
                  <group
                    name="LOTUS-def3Layer13"
                    position={[0, 60.841, -21.477]}
                  >
                    <mesh
                      name="LOTUS-def3Layer13_CARblack_0"
                      geometry={nodes["LOTUS-def3Layer13_CARblack_0"].geometry}
                      material={materials["CAR.black"]}
                    />
                  </group>
                  <group
                    name="LOTUS-def3Layer3"
                    position={[0, 2, 0]}
                    scale={[1.142, 1, 1]}
                  >
                    <mesh
                      name="LOTUS-def3Layer3_SHADE_0"
                      geometry={nodes["LOTUS-def3Layer3_SHADE_0"].geometry}
                      material={materials.SHADE}
                    />
                  </group>
                  <group
                    name="Camera"
                    position={[4168.26, 829, -6507.639]}
                    rotation={[Math.PI, -1.011, 3.033]}
                  >
                    <group name="Object_153" />
                  </group>
                  <group
                    name="Girl1_mesh"
                    position={[-31.155, -42.943, -6.97]}
                    rotation={[Math.PI, 0, 0]}
                    scale={0.9}
                  />
                  <group name="SOL01">
                    <mesh
                      name="SOL01_SOL_0"
                      geometry={nodes.SOL01_SOL_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group
                    name="Light_(1)"
                    position={[-3865.996, 1703.5, 466.641]}
                    rotation={[1.657, -0.519, 1.744]}
                  >
                    <group name="Object_147" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_148" />
                    </group>
                  </group>
                  <group
                    name="Light_(2)"
                    position={[4769.873, 1091.5, -18.936]}
                    rotation={[1.546, 0.275, -1.48]}
                  >
                    <group name="Object_150" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_151" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/car/car.gltf");
