/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\black_hole.gltf 
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-hole-e410da98b1e5445eae2acafaaa53587d
Title: Black Hole
*/

import React, { useRef } from "react";
import { Environment, OrbitControls, useGLTF } from "@react-three/drei";

export default function BlackHole(props) {
  const { nodes, materials } = useGLTF("/black_hole/black_hole.gltf");
  return (
    <>
      <OrbitControls />
      <Environment preset="sunset" />
      <group {...props} dispose={null} scale={0.1}>
        <group rotation={[-Math.PI / 2, -0.375, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                geometry={nodes.black_hole_black_hole_blackoutside_0.geometry}
                material={materials.black_hole_blackoutside}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_blackoutside_0_1.geometry}
                material={materials.black_hole_blackoutside}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_blackoutside_0_2.geometry}
                material={materials.black_hole_blackoutside}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_light3_0.geometry}
                material={materials.black_hole_light3}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_light2_0.geometry}
                material={materials.black_hole_light2}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_light1_0.geometry}
                material={materials.black_hole_light1}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_distortion_0.geometry}
                material={materials.black_hole_distortion}
              />
              <mesh
                geometry={nodes.black_hole_black_hole_center_0.geometry}
                material={materials.black_hole_center}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                geometry={nodes.black_hole_ring_ring_0.geometry}
                material={materials.ring}
              />
              <mesh
                geometry={nodes.black_hole_ring_ring2_0.geometry}
                material={materials.ring2}
              />
              <mesh
                geometry={nodes.black_hole_ring_ring2_0_1.geometry}
                material={materials.ring2}
              />
              <mesh
                geometry={nodes.black_hole_ring_ring2_0_2.geometry}
                material={materials.ring2}
              />
              <mesh
                geometry={nodes.black_hole_ring_ring2_0_3.geometry}
                material={materials.ring2}
              />
            </group>
            <mesh
              geometry={nodes.Planet_Planet_0.geometry}
              material={materials.Planet}
              position={[30802.896, 2286.717, 136477.797]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/black_hole/black_hole.gltf");
