/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\planets_and_satellites.gltf 
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/of-planes-and-satellites-db8f1c8cba3b464993e216acbf4a69b9
Title: Of Planes and Satellites
*/

import React, { useEffect, useRef } from "react";
import {
  Environment,
  OrbitControls,
  PerspectiveCamera,
  Stars,
  useGLTF,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Planets_and_satellites(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF(
    "/of_planes_and_satellites/planets_and_satellites.gltf"
  );
  useFrame(() => {
    groupRef.current.rotation.y = groupRef.current.rotation.y - Math.PI / 720;
  });
  return (
    <>
      {/* <ambientLight /> */}
      <directionalLight position={[-5, 0, -6]} />
      <Stars />
      <PerspectiveCamera
        position={[-2, 0, -6]}
        target={[13, 0, 0]}
        makeDefault
      />
      <OrbitControls
        minDistance={0}
        minZoom={5}
        maxZoom={10}
        enablePan={false}
      />
      <Environment preset="studio" />
      <group {...props} dispose={null} scale={50} ref={groupRef}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <lineSegments
              geometry={nodes.Object_4.geometry}
              material={materials.sat_gps_material}
            />
            <lineSegments
              geometry={nodes.Object_6.geometry}
              material={materials.sat_comms_material}
            />
            <lineSegments
              geometry={nodes.Object_8.geometry}
              material={materials.sat_tech_material}
            />
            <lineSegments
              geometry={nodes.Object_10.geometry}
              material={materials.sat_earth_material}
            />
            <lineSegments
              geometry={nodes.Object_12.geometry}
              material={materials.routes_material}
            />
            <lineSegments
              geometry={nodes.Object_13.geometry}
              material={materials.routes_material}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.earth}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/of_planes_and_satellites/planets_and_satellites.gltf");
