/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: abhayexe (https://sketchfab.com/abhayexe)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/happy-new-year-2026-211caa1f5bad463181124c9f96b5264a
Title: Happy New Year 2026!
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/new_year/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.8, 1, -0.354]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} position={[-0.7, 1.7, -0.319]} rotation={[Math.PI / 2, 0, 0]} scale={0.359} />
    </group>
  )
}

useGLTF.preload('/new_year/scene.gltf')

export default Scene;