/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ILilMitch (https://sketchfab.com/ILilMitch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/reaver-vandal-white-04f9851ace5c424492c327608b895e2c
Title: Reaver Vandal (White)
*/

import React, { useEffect, useRef } from "react";
import {
  Environment,
  OrbitControls,
  PerspectiveCamera,
  useGLTF,
} from "@react-three/drei";

export default function Reaver({ setBgColor, ...props }) {
  const { nodes, materials } = useGLTF("/reaver/reaver.gltf");
  useEffect(() => {
    console.log("hello");
    if (setBgColor) {
      setBgColor("grey");
    }
  }, []);
  return (
    <>
      <PerspectiveCamera position={[0, 0, -2]} makeDefault />
      <ambientLight />
      <OrbitControls />
      <Environment preset="sunset" />
      <group {...props} dispose={null}>
        <group position={[-0.2, 0, 0]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_6.geometry}
            material={materials.AK_Soulstealer_MI}
            skeleton={nodes.Object_6.skeleton}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.AK_Soulstealer_MI}
          position={[-0.2, 0, 0]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/reaver/reaver.gltf");
