/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gandhi.gltf 
Author: Stan (https://sketchfab.com/Stas_SayHallo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/gandhi-2d802195370c46f784827142022b61ce
Title: Gandhi
*/

import React, { useRef } from "react";
import { Text3D, useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Gandhi(props) {
  const currentDate = new Date();
  const value = parseInt(
    currentDate.getDate().toString() + currentDate.getMonth().toString()
  );
  console.log(currentDate.getHours())
  let message =
    value - 29 === 0
      ? "The Big Day"
      : value - 29 === -10
      ? "1 day to go"
      // : (currentDate.getHours() >= 19 && currentDate.getHours() <= 22 ) ? "Ghar Jao Beta !" : "Sabar Karo beta !";
      : (currentDate.getHours() >= 19 && currentDate.getHours() <= 22 ) ? "Idhar Aao Beta !" : "Increment Chahiye !";  
  const { nodes, materials } = useGLTF("/gandhi/gandhi.gltf");
  const material = new THREE.MeshBasicMaterial({ color: "#F5F5DC" });

  return (
    <>
      <Text3D
        position={[-2.7, 4.5, 0]}
        font="/helvetiker_regular.typeface.json"
        size={0.55}
        height={0.01}
        curveSegments={12}
        bevelEnabled
        bevelThickness={0.01}
        bevelSegments={5}
        bevelOffset={0}
        bevelSize={0.02}
        material={material}
      >
        {message}
      </Text3D>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.glasses_02_low_Gandi_0.geometry}
              material={materials.Gandi}
              position={[0, 0, -0.233]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.glasses_01_low_01_Gandi_0.geometry}
              material={materials.Gandi}
              position={[0, 0, -1.055]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.mustache_low_Gandi_0.geometry}
              material={materials.Gandi}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.eyebrows_low_Gandi_0.geometry}
              material={materials.Gandi}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.body_low_Gandi_0.geometry}
              material={materials.Gandi}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.glasses_01_low_02_Gandi_0.geometry}
              material={materials.Gandi}
              position={[0, 0, -1.055]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
            <mesh
              geometry={nodes.eyes_eye_0.geometry}
              material={materials.material}
              position={[-42.818, 272.563, -82.593]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={16.874}
            />
            <mesh
              geometry={nodes.glasses_03_low_glass_0.geometry}
              material={materials.glass}
              position={[0, 0, -0.233]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={100}
            />
          </group>
        </group>
      </group>
      <Text3D
        position={[-2.8, -2.2, 0]}
        font="/helvetiker_regular.typeface.json"
        size={0.6}
        height={0.01}
        curveSegments={12}
        bevelEnabled
        bevelThickness={0.01}
        bevelSegments={5}
        bevelOffset={0}
        bevelSize={0.02}
        material={material}
      >
        {(currentDate.getHours() >= 19 && currentDate.getHours() <= 22 ) ? 'Increment Deta Hoon' : 'Chal Bhag Yahase'}
      </Text3D>
    </>
  );
}

useGLTF.preload("/gandhi/gandhi.gltf");
